name             'windows_dns_record'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'A Chef resource for adding Windows DNS records'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
supports         'windows'
source_url       'https://github.com/chef-cookbooks/windows_dns_record'
issues_url       'https://github.com/chef-cookbooks/windows_dns_record/issues'
chef_version     '>= 13.0'
